### ISSUE TITLE
Linker issue with cubemx port to embitz1.11

### ISSUE THREAD

**Issue by ClockedLogic** [PeHackenberg/EmBitz-guides#1]
Hi Peter , Thanks kindly for putting this manual up. I have been struggling with porting cubemx to embitz until I saw your manual. I have made better progress so far apart from a linking issue which I'm hoping you can help me with.

I created a simply app in CubeMX to implement a simple Hello World example using USB FS virtual com port. It works in TrueStudio.  I've tried to follow your manual , I'm using an STM32F405RG on my own board, My version of Embitz seems to be slightly different in the compiler options screen.  Anyhow the code compiles under Embitz  but linking fails and I'm not sure why . I'm a novice at these issue. 
I've attached a copy of the build log and the project sources in a zip.
Regards 
Peter.
[build.log](https://github.com/peterhackenberg/EmBitz-guides/files/6889467/build.log)
[MX_USB_TEST.zip](https://github.com/peterhackenberg/EmBitz-guides/files/6889459/MX_USB_TEST.zip)

**Comment by peterhackenberg** [comment]
Hi,
sorry for my late answer, somehow I didn't receive a notification from github.
I was able to reproduce the same issue with your submitted files.
You just missed to tick:
> ☑ INCLUDE library Start files

![grafik](https://user-images.githubusercontent.com/28866559/145216366-2c5e88c5-2ec5-4c74-b1e4-18ffccfae76e.png)

Tested with EmBitz 2.10, and linking fine.

I still do like EmBitz, but the workflow to port CubeMX projects to EmBitz is quite intense and error-prone. I do recommend using CubeIDE, The STM tools are becoming better and offer a very easy workflow for project setup and editing.
Best regards
Peter
